# Generated by Django 4.1.7 on 2023-03-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecastCollectorApi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Spot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("spot", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("dataSourceUrl", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="forecastdata",
            name="country",
            field=models.CharField(max_length=100),
        ),
    ]
