qodana:
   image:
      name: jetbrains/qodana-<linter>
      entrypoint: [""]
   script:
      - cd userService
      - qodana --save-report --results-dir=$CI_PROJECT_DIR/qodana
         --report-dir=$CI_PROJECT_DIR/qodana/report
   artifacts:
      paths:
         - qodana
