version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5673:5673"
      - "15673:15672"
    networks:
      - kong-net

  kong-database:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    networks:
      - kong-net

  kong-migrations:
    image: kong/kong-gateway:3.2.2.0
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kongpass
      KONG_PASSWORD: test
    command: kong migrations bootstrap
    networks:
      - kong-net

  kong-gateway:
    image: kong/kong-gateway:3.2.2.0
    environment:
      TZ: Europe/Berlin
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_LICENSE_DATA: ''
      KONG_DECLARATIVE_CONFIG: ./kong.yaml
      
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    networks:
      - kong-net
    volumes:
      - ./kong-gateway:/kong.yaml

  user-service:
    build: ./userService
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8005"
    volumes:
      - ./user-service:/app
    ports:
      - "8005:8005"
    depends_on:
      - kong-gateway
    networks:
      - kong-net


  forecast-collector:
    build: ./forecastCollector
    command:  sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8006"
    volumes:
      - ./forecast-collector:/app
    ports:
      - "8006:8006"
    depends_on:
      - kong-gateway
    networks:
      - kong-net

  forecast-provider:
    build: ./forecastProvider
    command:  sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8007"
    volumes:
      - ./forecast-provider:/app
    ports:
      - "8007:8007"
    depends_on:
      - kong-gateway
    networks:
      - kong-net

  surfsession-logger:
    build: ./surfSessionLogger
    command:  sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8008"
    volumes:
      - ./surfsession-logger:/app
    ports:
      - "8008:8008"
    depends_on:
      - kong-gateway
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge
