// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import URI from "./libs/urijs.js";
import http from 'k6/http';
import { Counter } from 'k6/metrics';
import encoding from 'k6/encoding';

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

let userCounter = new Counter('userCounter');
export default function() {
  //register
  let email = generateRandomString(10) + Math.floor(Math.random() * 10) + '@test.com'

  let registerBody = JSON.stringify({
    email: email, 
    skill_level: "beginner", 
    password: "test"
  });
  const register = http.post("http://143.244.197.166:8000/user/", registerBody)
  console.log(register)

 //login
  let encr = encoding.b64encode(`${email}:test`)
  const authHeader = `Basic ` + encr;
  const res = http.get("http://143.244.197.166:8000/login/",{ headers: { Authorization: authHeader } } )
  console.log(res)

  let token = res.json()['token']

 //surfsession get
  http.get("http://143.244.197.166:8000/surfsession/", {headers: { Authorization: `Bearer ${token}` }})

 //surfsession post
  let surfBody = JSON.stringify({
    date_time: "2023-01-01T11:05",
    country: "NL",
    spot: "Scheveningen",
    rating: 3
  });
  let surfHeader = {
    headers: {
      Authorization: "Bearer " + token,
      "Content-Type": "application/json"
    }
  };
  http.post("http://143.244.197.166:8000/surfsession/", surfBody, surfHeader)

}

function generateRandomString(length) {
  var characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  var randomString = '';
  
  for (var i = 0; i < length; i++) {
    var randomIndex = Math.floor(Math.random() * characters.length);
    randomString += characters.charAt(randomIndex);
  }
  
  return randomString;
}
