apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migrations
spec:
  template:
    spec:
      containers:
        - name: kong-migrations
          image: kong/kong-gateway:3.2.2.0
          env:
            - name: KONG_DATABASE
              value: postgres
            - name: KONG_PG_HOST
              value: db-postgresql-ams3-01613-do-user-14134273-0.b.db.ondigitalocean.com
            - name: KONG_PG_USER
              value: doadmin
            - name: KONG_PG_PASSWORD
              value: AVNS_hvslPrJ3fObDICkuk2i
            - name: KONG_PASSWORD
              value: test
          command: ["sh", "-c", "kong migrations bootstrap && tail -f /dev/null"]
      restartPolicy: Never

