apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-gateway
  template:
    metadata:
      labels:
        app: kong-gateway
    spec:
      containers:
        - name: kong-gateway
          image: kong/kong-gateway:3.2.2.0
          env:
            - name: TZ
              value: Europe/Berlin
            - name: KONG_DATABASE
              value: postgres
            - name: KONG_PG_HOST
              value: db-postgresql-ams3-69837-do-user-14134273-0.b.db.ondigitalocean.com
            - name: KONG_PG_PORT
              value: "25060"
            - name: KONG_PG_USER
              value: doadmin
            - name: KONG_PG_PASSWORD
              value: AVNS_tdqi_BmtjB5vC-iOdQh
            - name: KONG_PG_DATABASE
              value: defaultdb
            - name: KONG_PG_SSL
              value: "true"
            - name: KONG_PROXY_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_PROXY_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_LISTEN
              value: 0.0.0.0:8001
            - name: KONG_ADMIN_GUI_URL
              value: http://localhost:8002
            - name: KONG_LICENSE_DATA
              value: ''
            - name: KONG_PROXY_SSL_CERT
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: tls.crt
            - name: KONG_PROXY_SSL_CERT_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: tls.key

          ports:
            - containerPort: 8000
            - containerPort: 8443
            - containerPort: 8001
            - containerPort: 8444
            - containerPort: 8002
            - containerPort: 8445
            - containerPort: 8003
            - containerPort: 8004
---
apiVersion: v1
kind: Service
metadata:
  name: kong-gateway
spec:
  selector:
    app: kong-gateway
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: admin
      protocol: TCP
      port: 8002
      targetPort: 8002
    - name: admin2
      protocol: TCP
      port: 8001
      targetPort: 8001
    - name: admin3
      protocol: TCP
      port: 8003
      targetPort: 8003
    - name: admin4
      protocol: TCP
      port: 8004
      targetPort: 8004
    - name: admin5
      protocol: TCP
      port: 8444
      targetPort: 8444
    - name: admin6
      protocol: TCP
      port: 8445
      targetPort: 8445
  type: LoadBalancer

