apiVersion: v1
kind: Service
metadata:
  name: rabbit
spec:
  selector:
    app: rabbit
  ports:
    - port: 5672
      targetPort: 5672
      name: mq
    - port: 15672
      targetPort: 15672
      name: management
  type: LoadBalancer
