# Generated by Django 4.1.7 on 2023-03-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "userServiceAdmin",
            "0003_alter_customuser_options_alter_customuser_managers_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(name="customuser", options={},),
        migrations.AlterModelManagers(name="customuser", managers=[],),
        migrations.RemoveField(model_name="customuser", name="date_joined",),
        migrations.RemoveField(model_name="customuser", name="first_name",),
        migrations.RemoveField(model_name="customuser", name="groups",),
        migrations.RemoveField(model_name="customuser", name="is_active",),
        migrations.RemoveField(model_name="customuser", name="is_staff",),
        migrations.RemoveField(model_name="customuser", name="is_superuser",),
        migrations.RemoveField(model_name="customuser", name="last_name",),
        migrations.RemoveField(model_name="customuser", name="user_permissions",),
        migrations.AddField(
            model_name="customuser",
            name="admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="staff",
            field=models.BooleanField(default=False),
        ),
    ]
