# Generated by Django 4.1.7 on 2023-03-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surfSessionAdmin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surfsession",
            name="conditions",
            field=models.JSONField(blank=True),
        ),
    ]
