# Generated by Django 4.1.7 on 2023-03-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("surfSessionAdmin", "0002_alter_surfsession_conditions"),
    ]

    operations = [
        migrations.RemoveField(model_name="surfsession", name="conditions",),
    ]
