# Generated by Django 4.1.7 on 2023-03-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ForecastData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=2)),
                ("spot", models.CharField(max_length=100)),
                ("dateTime", models.DateTimeField()),
                ("waveHeight", models.FloatField()),
                ("wavePeriod", models.FloatField()),
                ("waveDirection", models.FloatField()),
                ("windDirection", models.FloatField()),
                ("windSpeed", models.FloatField()),
                ("tide", models.FloatField()),
            ],
        ),
    ]
