# Generated by Django 4.1.7 on 2023-03-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecastCollectorAdmin", "0002_spot_alter_forecastdata_country"),
    ]

    operations = [
        migrations.RenameField(model_name="spot", old_name="spot", new_name="name",),
        migrations.AlterField(
            model_name="forecastdata",
            name="spot",
            field=models.OneToOneField(
                on_delete=models.SET("Spot"),
                related_name="spot",
                to="forecastCollectorAdmin.spot",
            ),
        ),
    ]
