# Generated by Django 4.1.7 on 2023-03-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecastCollectorAdmin", "0003_rename_spot_spot_name_alter_forecastdata_spot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forecastdata",
            name="spot",
            field=models.ForeignKey(
                on_delete=models.SET("Spot"),
                related_name="spot",
                to="forecastCollectorAdmin.spot",
            ),
        ),
    ]
