# Generated by Django 4.1.7 on 2023-03-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forecastCollectorAdmin", "0004_alter_forecastdata_spot"),
    ]

    operations = [
        migrations.RemoveField(model_name="forecastdata", name="country",),
    ]
