# Generated by Django 4.1.7 on 2023-04-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecastCollectorAdmin", "0005_remove_forecastdata_country"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="forecastdata",
            constraint=models.UniqueConstraint(
                fields=("spot", "dateTime"), name="unique_spot_dateTime"
            ),
        ),
    ]
