services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "2432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - individual_kong-net
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:3003
    volumes:
      - .:/code
    ports:
      - "3003:3003"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - individual_kong-net
    depends_on:
      - db
networks:
  individual_kong-net:
    external: true