# Generated by Django 4.1.7 on 2023-03-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Spot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("dataSourceUrl", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ForecastData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dateTime", models.DateTimeField()),
                ("waveHeight", models.FloatField()),
                ("wavePeriod", models.FloatField()),
                ("waveDirection", models.FloatField()),
                ("windDirection", models.FloatField()),
                ("windSpeed", models.FloatField()),
                ("tide", models.FloatField()),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=models.SET("Spot"),
                        related_name="spot",
                        to="forecastProviderAdmin.spot",
                    ),
                ),
            ],
        ),
    ]
