name: Cypress CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - dev
      
jobs:
  Cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start Docker Compose
        run: docker-compose up -d
        
      - name: Cypress test
        working-directory: ./Ionic-Front-app
        run: |
         npm install
         npx cypress run
      


