name: Django CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        folder: ['userService', 'forecastProvider', 'forecastCollector', 'surfSessionLogger']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Debug
        run: |
          ls -l
          pwd
        working-directory: ${{ matrix.folder }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ${{ matrix.folder }}
      - name: Run Tests
        run: |
          python manage.py test
        working-directory: ${{ matrix.folder }}
