name: Zap
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Run Deck Sync
        uses: ./
        with:
          args: sync

      - name: Run Zap Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:8100'
